[package]
name = "self-repl"
version = "0.1.0"
authors = ["guangfuhe"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linefeed = "0.6"
rand="0.7.3"