[package]
name = "workspace"
version = "0.1.0"
authors = ["guangfuhe"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members=["add", "addone"]

[dependencies]
add = {path="add"}
addone = {path = "addone"}
